### ISSUE TITLE
Size of the Library

### ISSUE THREAD

**Issue by therealshabi** [gurleensethi/LiteUtilities#2]
It is advisable to have a library such that it has minimal impact on the App size, this library has almost 35 KB of JAR size + around 4.3MB of Dependencies JAR Size, so it is suggested to make them modular some way i.e if I want to have that Toast functionality, then I'll have to import the whole library although I have no use of RecyclerView Whatsoever so this will basically create an overhead for my app.
If you get what I mean

**Comment by gurleensethi** [comment]
The utility files are independent of each other and every feature has its own file, so if you want only the toast functionality the go ahead and download the [ToastUtils.kt](https://github.com/gurleensethi/LiteUtilities/blob/master/liteutils/src/main/java/com/thetechnocafe/gurleensethi/liteutils/ToastUtils.kt) file and place it into your project. Also make sure Kotlin support is enabled in your project.

**Comment by therealshabi** [comment]
Yes that could be a way, but that won't be a library then, that would work as a Gist or file which we have to copy in our project, ain't it?

**Comment by therealshabi** [comment]
Anyways good job Mr Developer, that would ease of many things 🥇  Thanks 👍

**Comment by gurleensethi** [comment]
This library covers API's that are used on a daily basis and are essential when developing any kind of app, so to a wider developers it will serve as is, but everyone is welcomed to just use the parts that are required.
