### ISSUE TITLE
RecyclerUtils doesn't keep the view id's

### ISSUE THREAD

**Issue by marc97** [gurleensethi/LiteUtilities#3]
Hello, 
One of the main functions of the ViewHolder is to keep the reference of the views ids. So, if you find those every time data bind listener is called, the perfomance will slow down. One thing you can do to solve this is making use of android-kotlin-extensions.

**Comment by gurleensethi** [comment]
Solved it, now the user has to provide the list of views that are required during data-binding before hand. Check out the updated RecyclerAdapter API.

Adding android-kotlin-extensions would have increased the size of library, still if you want that functionality, you can get it by adding the dependency to your own project.
Thanks!

**Comment by marc97** [comment]
I was just checking the code when I found the problem and I wanted to comment it. In fact, I've already wrote a class that also manages different types of views, integrated with RxJava and other stuff.
You're welcome!
