### ISSUE TITLE
What license are these libraries released under?

### ISSUE THREAD

**Issue by allowthere** [gurleensethi/LiteUtilities#5]

**Comment by Polyterative** [comment]
I need this too

**Comment by aksh1618** [comment]
Please add a suitable license to allow developers to use this library in their release apps. 
Based on your description, I'd recommend the [**MIT License**](https://choosealicense.com/licenses/mit/).
[Github's Official License Guide](https://choosealicense.com/)

**Comment by gurleensethi** [comment]
Added License.
