### ISSUE TITLE
having java version of LiteUtilities ??

### ISSUE THREAD

**Issue by pawanchauhan05** [gurleensethi/LiteUtilities#6]
want a java version of this lib.
is that possible ???

**Comment by gurleensethi** [comment]
Kotlin works seamlessly with JAVA, i.e. you can add this library to your JAVA project and use the required classes and functions. Please read this link for further details https://kotlinlang.org/docs/reference/java-to-kotlin-interop.html

**Comment by pawanchauhan05** [comment]
is recycler view supports multiple views ??

**Comment by gurleensethi** [comment]
Curently there isn't support for multiple view types in recycler vew.

**Comment by pawanchauhan05** [comment]
can you provide java file of RecyclerAdapterUtil so i can extend it for multiple views ?

**Comment by gurleensethi** [comment]
The code for RecyclerAdapterUtil is written in Kotlin and can be found [here](https://github.com/gurleensethi/LiteUtilities/blob/master/liteutils/src/main/java/com/thetechnocafe/gurleensethi/liteutils/RecyclerUtils.kt).

**Comment by pawanchauhan05** [comment]
yes but i want java file not kotlin.

**Comment by gurleensethi** [comment]
There is no java file for RecyclerAdapterUtil.
